# Generated by Django 5.2.8 on 2026-05-06 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Judgment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=200)),
                ('uploaded_pdf', models.FileField(upload_to='judgments/')),
                ('raw_text', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ActionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(max_length=200)),
                ('court_name', models.CharField(max_length=300)),
                ('judgment_date', models.CharField(blank=True, max_length=50)),
                ('parties', models.CharField(blank=True, max_length=500)),
                ('judgment_summary', models.TextField(blank=True)),
                ('directives', models.JSONField(default=list)),
                ('compliance_deadline', models.CharField(blank=True, max_length=100)),
                ('appeal_recommended', models.BooleanField(default=False)),
                ('appeal_reason', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('judgment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='action_plan', to='core.judgment')),
            ],
        ),
        migrations.CreateModel(
            name='OfficerReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField()),
                ('notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(auto_now_add=True)),
                ('action_plan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='core.actionplan')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
